name = "uart_g4xx"
description = "UART driver"
version = "0.1.0"

authors = ["CÃ©lian Aldehuelo-Mateos, Vladislav Kupin"]
maintainers = ["Vladislav Kupin <vlad.kupin@proton.me>"]
maintainers-logins = ["axterd"]
licenses = "BSD-3-Clause"
website = "https://github.com/evolutek"
tags = ["embedded", "stm32", "stellarhal", "evolutek"]

[[depends-on]]
gnat_arm_elf = ">=12.1.0"
stm32g4_hal = "*"

[origin]
commit = "260b7a7f4971807a3b9d76e5073d28afe422e47f"
url = "git+https://github.com/evolutek/stellardrive.git"
subdir = "uart/uart_g4xx"